name: Cypress Tests
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1]

    steps:
      - name: Checkout
        uses: actions/checkout@v4      
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
           record: true
           parallel: true
           command: npx cypress run --record --browser chrome --headless --env tags=@Regression
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.5
